/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/csrf/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Issue a CSRF cookie for browser clients. */
    get: operations["getApiV1AuthCsrf"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/health/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Health check endpoint (no auth required). */
    get: operations["getApiV1AuthHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiV1AuthLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get or update current user profile. */
    get: operations["getApiV1AuthMe"];
    /** @description Get or update current user profile. */
    put: operations["putApiV1AuthMe"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/metrics/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Expose bounded Prometheus metrics to staff or configured scrapers. */
    get: operations["getApiV1AuthMetrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/ready/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Check dependencies required to accept production traffic. */
    get: operations["getApiV1AuthReady"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiV1AuthRefresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Register a new user and return user data. */
    post: operations["postApiV1AuthRegister"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/session/login/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Create a Django session for first-party browser clients. */
    post: operations["postApiV1AuthSessionLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/session/logout/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Clear a Django browser session. */
    post: operations["postApiV1AuthSessionLogout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List all chats for the current user. */
    get: operations["getApiV1Chats"];
    put?: never;
    /** @description Create a new chat session. */
    post: operations["postApiV1Chats"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/discover/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Trigger scripture auto-discovery. */
    post: operations["postApiV1ChatsDiscover"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get a chat with its full message history. */
    get: operations["getApiV1ChatsById"];
    put?: never;
    post?: never;
    /** @description Delete a chat session. */
    delete: operations["deleteApiV1ChatsById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{id}/archive/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Archive a chat session. */
    post: operations["postApiV1ChatsByIdArchive"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{id}/messages/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Cursor-paginated messages for one chat. */
    get: operations["getApiV1ChatsByIdMessages"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{id}/rename/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Rename a chat session. */
    patch: operations["patchApiV1ChatsByIdRename"];
    trace?: never;
  };
  "/api/v1/chats/{id}/runs/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Create a durable generation run. */
    post: operations["postApiV1ChatsByIdRuns"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chats/{id}/unarchive/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Restore an archived chat session. */
    post: operations["postApiV1ChatsByIdUnarchive"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/catalog/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Read active catalog metadata and allow staff-only file refresh. */
    get: operations["getApiV1ModelsCatalog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/catalog/refresh/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read active catalog metadata and allow staff-only file refresh. */
    post: operations["postApiV1ModelsCatalogRefresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/connections/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Read sanitized provider connection status for the current user. */
    get: operations["getApiV1ModelsConnections"];
    put?: never;
    /** @description Read sanitized provider connection status for the current user. */
    post: operations["postApiV1ModelsConnections"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/connections/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Read sanitized provider connection status for the current user. */
    get: operations["getApiV1ModelsConnectionsById"];
    put?: never;
    post?: never;
    /** @description Read sanitized provider connection status for the current user. */
    delete: operations["deleteApiV1ModelsConnectionsById"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/connections/{id}/probe/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Read sanitized provider connection status for the current user. */
    post: operations["postApiV1ModelsConnectionsByIdProbe"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/installations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Create and inspect one-at-a-time staff local installation jobs. */
    get: operations["getApiV1ModelsInstallations"];
    put?: never;
    /** @description Create and inspect one-at-a-time staff local installation jobs. */
    post: operations["postApiV1ModelsInstallations"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/installations/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Create and inspect one-at-a-time staff local installation jobs. */
    get: operations["getApiV1ModelsInstallationsById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/installations/{id}/cancel/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Create and inspect one-at-a-time staff local installation jobs. */
    post: operations["postApiV1ModelsInstallationsByIdCancel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/preferences/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get or update the authenticated user's model preference. */
    get: operations["getApiV1ModelsPreferencesMe"];
    /** @description Get or update the authenticated user's model preference. */
    put: operations["putApiV1ModelsPreferencesMe"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/profiles/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List selectable enabled model profiles. */
    get: operations["getApiV1ModelsProfiles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/profiles/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List selectable enabled model profiles. */
    get: operations["getApiV1ModelsProfilesById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Durable generation run endpoints. */
    get: operations["getApiV1RunsById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/cancel/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Durable generation run endpoints. */
    post: operations["postApiV1RunsByIdCancel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{id}/events/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Durable generation run endpoints. */
    get: operations["getApiV1RunsByIdEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scriptures/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description ViewSet for listing and retrieving scriptures. */
    get: operations["getApiV1Scriptures"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scriptures/indexing-jobs/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Staff-only observability endpoint for index job progress and failures. */
    get: operations["getApiV1ScripturesIndexingJobs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scriptures/indexing-jobs/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Staff-only observability endpoint for index job progress and failures. */
    get: operations["getApiV1ScripturesIndexingJobsById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scriptures/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description ViewSet for listing and retrieving scriptures. */
    get: operations["getApiV1ScripturesById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scriptures/{id}/reindex/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Queue a staff-authorized reindex and return its durable job record. */
    post: operations["postApiV1ScripturesByIdReindex"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scriptures/{id}/rollback/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description ViewSet for listing and retrieving scriptures. */
    post: operations["postApiV1ScripturesByIdRollback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scriptures/{id}/versions/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description ViewSet for listing and retrieving scriptures. */
    get: operations["getApiV1ScripturesByIdVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CustomTokenObtainPair: {
      /** Format: email */
      email: string;
      password: string;
    };
    IndexingJob: {
      readonly chunks_indexed?: number;
      /** Format: date-time */
      readonly created_at?: string;
      readonly error_message?: string;
      /** Format: date-time */
      readonly finished_at?: string | null;
      readonly id?: number;
      readonly index_version?: string | null;
      readonly progress?: number;
      readonly scripture?: string;
      readonly scripture_name?: string;
      /** Format: date-time */
      readonly started_at?: string | null;
      /** @enum {string} */
      readonly status?: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
      readonly volumes_processed?: number;
    };
    ModelConnection: {
      /** Format: date-time */
      readonly created_at?: string;
      /** @enum {string} */
      readonly dialect?:
        "openai_compatible" | "ollama_compatible" | "builtin_ollama";
      /** Format: uri */
      readonly endpoint_url?: string;
      /** Format: uuid */
      readonly id?: string;
      /** Format: date-time */
      readonly last_checked_at?: string | null;
      readonly name?: string;
      /** Format: date-time */
      readonly remote_data_consent_at?: string | null;
      readonly sanitized_detail?: string;
      /** @enum {string} */
      readonly status?:
        | "disconnected"
        | "checking"
        | "connected"
        | "degraded"
        | "auth_invalid"
        | "endpoint_invalid"
        | "unreachable"
        | "rate_limited"
        | "quota_limited"
        | "model_unavailable";
      /** Format: date-time */
      readonly updated_at?: string;
    };
    ModelConnectionCreate: {
      api_key?: string;
      /** @enum {string} */
      dialect: "openai_compatible" | "ollama_compatible";
      /** Format: uri */
      endpoint_url: string;
      model_id: string;
      name: string;
      remote_data_consent: boolean;
    };
    ModelInstallationCreate: {
      entry_id: string;
      /** @default false */
      keep_source: boolean;
    };
    ModelInstallationJob: {
      /** Format: date-time */
      readonly created_at?: string;
      readonly error_code?: string;
      /** Format: date-time */
      readonly finished_at?: string | null;
      /** Format: uuid */
      readonly id?: string;
      readonly keep_source?: boolean;
      readonly model_profile?: string | null;
      readonly ollama_tag?: string;
      readonly qualification?: Record<string, never>;
      /** Format: date-time */
      readonly started_at?: string | null;
      /** @enum {string} */
      readonly status?:
        "pending" | "running" | "succeeded" | "failed" | "cancelled";
    };
    ModelProfile: {
      readonly connection?: string | null;
      /** @default  */
      readonly connection_dialect: string;
      /** @default  */
      readonly connection_status: string;
      readonly context_window?: number;
      /** Format: uuid */
      readonly id?: string;
      readonly is_admin_default?: boolean;
      readonly is_enabled?: boolean;
      readonly max_output_tokens?: number;
      readonly model_id?: string;
      readonly name?: string;
      readonly temperature?: number;
    };
    Register: {
      /** Format: email */
      email: string;
      password: string;
      password_confirm: string;
      spiritual_name?: string;
    };
    Scripture: {
      readonly active_index_version?: string;
      /** Format: date-time */
      readonly created_at?: string;
      readonly current_indexing_job?: {
        readonly chunks_indexed?: number;
        readonly progress?: number;
        /** @enum {string} */
        readonly status?: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        readonly volumes_processed?: number;
      };
      description?: string;
      folder_path: string;
      readonly id?: number;
      is_indexed?: boolean;
      /** Format: date-time */
      last_indexed_at?: string | null;
      name: string;
      total_pages?: number;
      total_volumes?: number;
      readonly volumes?: {
        file_name: string;
        file_path: string;
        /** Format: int64 */
        file_size?: number;
        readonly id?: number;
        mtime?: number;
        page_count?: number;
      }[];
    };
    TokenRefresh: {
      readonly access?: string;
      refresh: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getApiV1AuthCsrf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  getApiV1AuthHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  postApiV1AuthLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CustomTokenObtainPair"];
        "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPair"];
        "multipart/form-data": components["schemas"]["CustomTokenObtainPair"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomTokenObtainPair"];
        };
      };
    };
  };
  getApiV1AuthMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  putApiV1AuthMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiV1AuthMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  getApiV1AuthReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  postApiV1AuthRefresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TokenRefresh"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
        "multipart/form-data": components["schemas"]["TokenRefresh"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  postApiV1AuthRegister: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Register"];
        "application/x-www-form-urlencoded": components["schemas"]["Register"];
        "multipart/form-data": components["schemas"]["Register"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Register"];
        };
      };
    };
  };
  postApiV1AuthSessionLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  postApiV1AuthSessionLogout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiV1Chats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  postApiV1Chats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  postApiV1ChatsDiscover: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiV1ChatsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  deleteApiV1ChatsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  postApiV1ChatsByIdArchive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiV1ChatsByIdMessages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  patchApiV1ChatsByIdRename: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  postApiV1ChatsByIdRuns: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  postApiV1ChatsByIdUnarchive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiV1ModelsCatalog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  postApiV1ModelsCatalogRefresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiV1ModelsConnections: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ModelConnection"][];
          };
        };
      };
    };
  };
  postApiV1ModelsConnections: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ModelConnectionCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["ModelConnectionCreate"];
        "multipart/form-data": components["schemas"]["ModelConnectionCreate"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelConnectionCreate"];
        };
      };
    };
  };
  getApiV1ModelsConnectionsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelConnection"];
        };
      };
    };
  };
  deleteApiV1ModelsConnectionsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  postApiV1ModelsConnectionsByIdProbe: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ModelConnection"];
        "application/x-www-form-urlencoded": components["schemas"]["ModelConnection"];
        "multipart/form-data": components["schemas"]["ModelConnection"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelConnection"];
        };
      };
    };
  };
  getApiV1ModelsInstallations: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ModelInstallationJob"][];
          };
        };
      };
    };
  };
  postApiV1ModelsInstallations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ModelInstallationCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["ModelInstallationCreate"];
        "multipart/form-data": components["schemas"]["ModelInstallationCreate"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelInstallationCreate"];
        };
      };
    };
  };
  getApiV1ModelsInstallationsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this model installation job. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelInstallationJob"];
        };
      };
    };
  };
  postApiV1ModelsInstallationsByIdCancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this model installation job. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ModelInstallationJob"];
        "application/x-www-form-urlencoded": components["schemas"]["ModelInstallationJob"];
        "multipart/form-data": components["schemas"]["ModelInstallationJob"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelInstallationJob"];
        };
      };
    };
  };
  getApiV1ModelsPreferencesMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  putApiV1ModelsPreferencesMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getApiV1ModelsProfiles: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ModelProfile"][];
          };
        };
      };
    };
  };
  getApiV1ModelsProfilesById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelProfile"];
        };
      };
    };
  };
  getApiV1RunsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
          "text/event-stream": unknown;
        };
      };
    };
  };
  postApiV1RunsByIdCancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": unknown;
        "application/x-www-form-urlencoded": unknown;
        "multipart/form-data": unknown;
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
          "text/event-stream": unknown;
        };
      };
    };
  };
  getApiV1RunsByIdEvents: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
          "text/event-stream": unknown;
        };
      };
    };
  };
  getApiV1Scriptures: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Scripture"][];
          };
        };
      };
    };
  };
  getApiV1ScripturesIndexingJobs: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IndexingJob"][];
          };
        };
      };
    };
  };
  getApiV1ScripturesIndexingJobsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IndexingJob"];
        };
      };
    };
  };
  getApiV1ScripturesById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Scripture. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Scripture"];
        };
      };
    };
  };
  postApiV1ScripturesByIdReindex: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Scripture. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Scripture"];
        "application/x-www-form-urlencoded": components["schemas"]["Scripture"];
        "multipart/form-data": components["schemas"]["Scripture"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Scripture"];
        };
      };
    };
  };
  postApiV1ScripturesByIdRollback: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Scripture. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Scripture"];
        "application/x-www-form-urlencoded": components["schemas"]["Scripture"];
        "multipart/form-data": components["schemas"]["Scripture"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Scripture"];
        };
      };
    };
  };
  getApiV1ScripturesByIdVersions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A unique integer value identifying this Scripture. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Scripture"];
        };
      };
    };
  };
}
