# Generated by Django 5.2.14 on 2026-06-21 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scripture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("folder_path", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("total_volumes", models.IntegerField(default=0)),
                ("total_pages", models.IntegerField(default=0)),
                ("is_indexed", models.BooleanField(default=False)),
                ("last_indexed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Scripture",
                "verbose_name_plural": "Scriptures",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=500)),
                ("file_path", models.CharField(max_length=1000)),
                ("file_size", models.BigIntegerField(default=0)),
                ("page_count", models.IntegerField(default=0)),
                ("mtime", models.FloatField(default=0.0)),
                (
                    "scripture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="scriptures.scripture",
                    ),
                ),
            ],
            options={
                "ordering": ["file_name"],
            },
        ),
    ]
