# Generated by Django 5.2.14 on 2026-06-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scriptures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volume",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
