# Generated by Django 6.0.7 on 2026-07-30 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scriptures", "0003_indexingjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptureIndexVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("qualified", "Qualified"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="building",
                        max_length=20,
                    ),
                ),
                ("embedding_model", models.CharField(max_length=200)),
                ("source_manifest", models.JSONField(default=list)),
                ("qualification", models.JSONField(blank=True, default=dict)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("volume_count", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("qualified_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scripture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_versions",
                        to="scriptures.scripture",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="indexingjob",
            name="index_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="scriptures.scriptureindexversion",
            ),
        ),
        migrations.AddField(
            model_name="scripture",
            name="active_index_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_scriptures",
                to="scriptures.scriptureindexversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="indexingjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "RUNNING"])),
                fields=("scripture",),
                name="uniq_active_scripture_indexing_job",
            ),
        ),
        migrations.AddIndex(
            model_name="scriptureindexversion",
            index=models.Index(
                fields=["scripture", "status"], name="scriptures__scriptu_abc11a_idx"
            ),
        ),
    ]
