# Generated by Django 5.2.14 on 2026-06-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scripture", models.CharField(db_index=True, max_length=200)),
                ("file_name", models.CharField(max_length=500)),
                ("page", models.IntegerField()),
                ("chunk_text", models.TextField()),
                ("chunk_type", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("embedding", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_chunks",
                "indexes": [
                    models.Index(
                        fields=["scripture"], name="document_ch_scriptu_146d3c_idx"
                    )
                ],
            },
        ),
    ]
