# Generated by Django 6.0.7 on 2026-07-26 03:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("source", models.CharField(default="whichllm", max_length=80)),
                ("profile_hash", models.CharField(max_length=128, unique=True)),
                ("whichllm_version", models.CharField(blank=True, max_length=80)),
                ("catalog_version", models.CharField(blank=True, max_length=80)),
                ("driver_fingerprint", models.CharField(blank=True, max_length=160)),
                ("payload", models.JSONField(default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("stale", models.BooleanField(db_index=True, default=False)),
                ("scanned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "dialect",
                    models.CharField(
                        choices=[
                            ("openai_compatible", "OpenAI-compatible"),
                            ("ollama_compatible", "Ollama-compatible"),
                            ("builtin_ollama", "Built-in Ollama"),
                        ],
                        max_length=40,
                    ),
                ),
                ("endpoint_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disconnected", "Disconnected"),
                            ("checking", "Checking"),
                            ("connected", "Connected"),
                            ("degraded", "Degraded"),
                            ("auth_invalid", "Auth invalid"),
                            ("endpoint_invalid", "Endpoint invalid"),
                            ("unreachable", "Unreachable"),
                            ("rate_limited", "Rate limited"),
                            ("quota_limited", "Quota limited"),
                            ("model_unavailable", "Model unavailable"),
                        ],
                        db_index=True,
                        default="disconnected",
                        max_length=40,
                    ),
                ),
                ("sanitized_detail", models.CharField(blank=True, max_length=240)),
                ("dns_pins", models.JSONField(blank=True, default=list)),
                ("remote_data_consent_at", models.DateTimeField(blank=True, null=True)),
                ("encrypted_api_key", models.TextField(blank=True)),
                ("api_key_nonce", models.CharField(blank=True, max_length=80)),
                ("key_version", models.PositiveSmallIntegerField(default=1)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModelProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("model_id", models.CharField(max_length=180)),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("is_admin_default", models.BooleanField(default=False)),
                ("context_window", models.PositiveIntegerField(default=8192)),
                ("max_output_tokens", models.PositiveIntegerField(default=1024)),
                ("temperature", models.FloatField(default=0.2)),
                ("concurrency_limit", models.PositiveSmallIntegerField(default=1)),
                ("qualification", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="llm.modelconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModelInstallationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("active_lock", models.BooleanField(default=True, editable=False)),
                ("catalog_entry", models.JSONField(default=dict)),
                ("source_sha256", models.CharField(max_length=64)),
                ("source_size", models.PositiveBigIntegerField()),
                ("import_path", models.CharField(blank=True, max_length=500)),
                ("ollama_tag", models.CharField(blank=True, max_length=180)),
                ("keep_source", models.BooleanField(default=False)),
                ("qualification", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_installation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installation_jobs",
                        to="llm.modelprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserModelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_fallback_profile_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_users",
                        to="llm.modelprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="modelconnection",
            index=models.Index(
                fields=["user", "status"], name="llm_modelco_user_id_0755d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelconnection",
            index=models.Index(
                fields=["dialect", "status"], name="llm_modelco_dialect_181f98_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_admin_default", True)),
                fields=("is_admin_default",),
                name="uniq_enabled_admin_default_model_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelinstallationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "running"])),
                fields=("active_lock",),
                name="uniq_active_model_installation_job",
            ),
        ),
    ]
