# Generated by Django 6.0.7 on 2026-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_seed_builtin_ollama_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCatalogRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("sequence", models.PositiveIntegerField(unique=True)),
                ("version", models.CharField(max_length=80, unique=True)),
                ("key_id", models.CharField(max_length=80)),
                ("catalog_hash", models.CharField(max_length=64, unique=True)),
                ("signature", models.CharField(max_length=160)),
                ("payload", models.JSONField()),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("active", models.BooleanField(db_index=True, default=False)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-sequence"],
            },
        ),
    ]
